#!/bin/bash
#Aaron Hong
#4/16/23

if [ $# -lt 1 ]; then
  echo "Usage: spellcheck filename ..." >&2
  exit 1
fi
while [ $# -gt 0 ]; do
  if [ ! -f "$1" ]; then
    echo "error: "$1" does not exist - skipping" >&2
    shift
  else
    if [ ! -f "$1".spelling ]; then
      echo "creating "$1".spelling"
    else
      echo "replacing "$1".spelling"
      rm "$1".spelling
      touch "$1".spelling
    fi
    while read line; do
      for word in $line; do
        if ! grep -qix "$word" /usr/share/dict/words; then
	  echo "$word" >> "$1".spelling
        fi 
      done
    done < "$1"
    count=$(tr ' ' '\n' < "$1".spelling | wc -w)
    unique_count=$(tr ' ' '\n' < "$1".spelling | sort | uniq | wc -l)
    echo "processed $1 and found $count spelling errors $unique_count of which are unique"
    shift
  fi
done
exit 0
