#!/bin/bash
#Aaron Hong
#4/14/23

if [ -e "$1" ]; then
  echo "Error: Output file should not exist" >&2
  exit 1
fi
if [ $# -lt 2 ]; then
  echo "Usage: combine outputfilename [inputfilename ...]" >&2
  exit 1
fi
output="$1"
shift
cat "$@" &>> $output
exit 0
